project:
  type: website
  output-dir: docs
        
website:
  title: "Nicol&oacute; Foppa Pedretti"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics"
        contents: 
          - href: about.qmd
            text: "Extended resume"
          - href: add_resume.qmd
            text: "Publications"
      - section: "Projects"
        contents:
          - href: projects/gps/gps_analysis_nlme.qmd
            text: "Heart rate recovery analysis"
          - href: projects/portfolio/solar_forecast/solar_forecast_new.qmd
            text: "Solar energy forecast"
          - href: projects/portfolio/salmon/salmon_farming.qmd
            text: "Salmon farming model"  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


