project:
  type: website
  output-dir: docs

website:
  title: "Nicolo Foppa Pedretti"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    fontsize: smaller
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


