project:
  type: website
  output-dir: docs
        
website:
  title: "Nicolo Foppa Pedretti"
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics"
        contents: 
          - about.qmd
      - section: "Layout"
        contents:
          - add_resume.qmd
          - href: projects/gps/gps_analysis_nlme.qmd
            text: "Sales Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


